version: '3'
services:
  server:
    image: reimashi/web-3d-viewer:latest
    restart: always
    volumes:
      - models:/client/models
      - database:/database
    environment:
      WEB_PORT: 4080
      WEB_USER: admin
      WEB_PASS: admin
      WEB_AUTH_ENABLE: false
      STATIC_PATH: /client
      DATABASE_PATH: /database
    labels:
      traefik.enable: "true"
      traefik.port: "4080"
      traefik.frontend.rule: "Host:3d.aitorgf.com"
      traefik.frontend.entryPoints: "http"
      traefik.default.protocol: "http"

volumes:
  models:
  database: